export const BUSINESS_REGISTER_REQUEST = "BUSINESS_REGISTER_REQUEST";
export const BUSINESS_REGISTER_SUCCESS = "BUSINESS_REGISTER_SUCCESS";
export const BUSINESS_REGISTER_FAIL = "BUSINESS_REGISTER_FAIL";
export const BUSINESS_REGISTER_DELETE = "BUSINESS_REGISTER_DELETE";

export const BUSINESS_LOGIN_REQUEST = "BUSINESS_LOGIN_REQUEST";
export const BUSINESS_LOGIN_SUCCESS = "BUSINESS_LOGIN_SUCCESS";
export const BUSINESS_LOGIN_FAIL = "BUSINESS_LOGIN_FAIL";
export const BUSINESS_LOGIN_DELETE = "BUSINESS_LOGIN_DELETE";

export const BUSINESS_LOGIN_OAUTH_REQUEST = "BUSINESS_OAUTH_LOGIN_REQUEST";
export const BUSINESS_LOGIN_OAUTH_SUCCESS = "BUSINESS_OAUTH_LOGIN_SUCCESS";
export const BUSINESS_LOGIN_OAUTH_FAIL = "BUSINESS_OAUTH_LOGIN_FAIL";
export const BUSINESS_LOGIN_OAUTH_DELETE = "BUSINESS_OAUTH_LOGIN_DELETE";

export const BUSINESS_LOGOUT_REQUEST = "BUSINESS_LOGOUT_REQUEST";
export const BUSINESS_LOGOUT_SUCCESS = "BUSINESS_LOGOUT_SUCCESS";
export const BUSINESS_LOGOUT_FAIL = "BUSINESS_LOGOUT_FAIL";
export const BUSINESS_LOGOUT_DELETE = "BUSINESS_LOGOUT_DELETE";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";
export const BUSINESS_DETAILS_EDIT = "BUSINESS_DETAILS_EDIT";
export const BUSINESS_DETAILS_DELETE = "BUSINESS_DETAILS_DELETE";
export const BUSINESS_DETAILS_LOGIN_TOKEN = "BUSINESS_DETAILS_TOKEN";

export const BUSINESS_DETAILS_UPDATE_REQUEST =
  "BUSINESS_DETAILS_UPDATE_REQUEST";
export const BUSINESS_DETAILS_UPDATE_SUCCESS =
  "BUSINESS_DETAILS_UPDATE_SUCCESS";
export const BUSINESS_DETAILS_UPDATE_FAIL = "BUSINESS_DETAILS_UPDATE_FAIL";
