export const CASH_REGISTER_REQUEST = "CASH_REGISTER_REQUEST";
export const CASH_REGISTER_SUCCESS = "CASH_REGISTER_SUCCESS";
export const CASH_REGISTER_FAIL = "CASH_REGISTER_FAIL";
export const CASH_REGISTER_DELETE = "CASH_REGISTER_DELETE";

export const CASH_GET_REQUEST = "CASH_GET_REQUEST";
export const CASH_GET_SUCCESS = "CASH_GET_SUCCESS";
export const CASH_GET_FAIL = "CASH_GET_FAIL";
export const CASH_GET_DELETE = "CASH_GET_DELETE";

export const CASH_UPDATE_REQUEST = "CASH_UPDATE_REQUEST";
export const CASH_UPDATE_SUCCESS = "CASH_UPDATE_SUCCESS";
export const CASH_UPDATE_FAIL = "CASH_UPDATE_FAIL";
export const CASH_UPDATE_DELETE = "CASH_UPDATE_DELETE";
