export const INVESTMENT_ADD_REQUEST = "INVESTMENT_ADD_REQUEST";
export const INVESTMENT_ADD_SUCCESS = "INVESTMENT_ADD_SUCCESS";
export const INVESTMENT_ADD_FAIL = "INVESTMENT_ADD_FAIL";
export const INVESTMENT_ADD_DELETE = "INVESTMENT_ADD_DELETE";

export const INVESTMENT_GET_REQUEST = "INVESTMENT_GET_REQUEST";
export const INVESTMENT_GET_SUCCESS = "INVESTMENT_GET_SUCCESS";
export const INVESTMENT_GET_FAIL = "INVESTMENT_GET_FAIL";
export const INVESTMENT_GET_DELETE = "INVESTMENT_GET_DELETE";

export const INVESTMENT_UPDATE_REQUEST = "INVESTMENT_UPDATE_REQUEST";
export const INVESTMENT_UPDATE_SUCCESS = "INVESTMENT_UPDATE_SUCCESS";
export const INVESTMENT_UPDATE_FAIL = "INVESTMENT_UPDATE_FAIL";
export const INVESTMENT_UPDATE_DELETE = "INVESTMENT_UPDATE_DELETE";

export const INVESTMENT_DELETE_REQUEST = "INVESTMENT_DELETE_REQUEST";
export const INVESTMENT_DELETE_SUCCESS = "INVESTMENT_DELETE_SUCCESS";
export const INVESTMENT_DELETE_FAIL = "INVESTMENT_DELETE_FAIL";
export const INVESTMENT_DELETE_DELETE = "INVESTMENT_DELETE_DELETE";

export const INVESTMENT_DATA_ADDONE = "INVESTMENT_DATA_ADDONE";
export const INVESTMENT_DATA_ADDMANY = "INVESTMENT_DATA_ADDMANY";
export const INVESTMENT_DATA_UPDATE = "INVESTMENT_DATA_UPDATE";
export const INVESTMENT_DATA_DELETEONE = "INVESTMENT_DATA_DELETEONE";
export const INVESTMENT_DATA_DELETE = "INVESTMENT_DATA_DELETE";
