export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_DELETE = "USER_REGISTER_DELETE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_DELETE = "USER_LOGIN_DELETE";

export const USER_LOGIN_OAUTH_REQUEST = "USER_OAUTH_LOGIN_REQUEST";
export const USER_LOGIN_OAUTH_SUCCESS = "USER_OAUTH_LOGIN_SUCCESS";
export const USER_LOGIN_OAUTH_FAIL = "USER_OAUTH_LOGIN_FAIL";
export const USER_LOGIN_OAUTH_DELETE = "USER_OAUTH_LOGIN_DELETE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_DELETE = "USER_LOGOUT_DELETE";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_EDIT = "USER_DETAILS_EDIT";
export const USER_DETAILS_DELETE = "USER_DETAILS_DELETE";

export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAIL = "USER_DETAILS_UPDATE_FAIL";
